### ISSUE TITLE
Light-Mode as default

### ISSUE THREAD

**Issue by suther** [nicolasprigent/Dokuwiki-Kiwiki-Theme#29]
Is it possible to set the LightMode as default. 
From time to time, if I come back to my wiki, it's set to darkmode. I dislike this.

It would be very nice if there would be an option in the settings to just force the preferred mode - and also to hide the "mode-switch-button" in the frontend optionally too.

**Comment by nicolasprigent** [comment]
Hello @suther I've made an update to the js code, because the cookie was not set on the root path, so each pages was getting it's own cookie :/ now when you click on the theme switcher button, the chosen theme stays in place on each pages (you might need to delete cookies on your wiki domain).

**Comment by suther** [comment]
Ok, but what if cookies are cleared ? What will be the default-color?
Would be nice to have a way in the options to force one of both as default (even if cookies are removed, and user come back)

**Comment by nicolasprigent** [comment]
The default color is the system color, like in windows, if you have your system using dark colors, the website will be dark. I'll make some option to force the theme color, I have to think about it.

**Comment by nicolasprigent** [comment]
hello @suther , you now have a new option in the settings to set and force the default theme : you can choose to set light theme by default, and force it so that everyone would have this theme visible. Forcing the theme disables the button in the header.
![image](https://github.com/user-attachments/assets/368ff080-a4ab-4881-b9c2-f9eec04d7828)
Let me know if that works for you ?

**Comment by suther** [comment]
Works great. Thank you for your effort!
