### ISSUE TITLE
Question: Different logo for dark and light theme

### ISSUE THREAD

**Issue by christianprim** [nicolasprigent/Dokuwiki-Kiwiki-Theme#31]
Hello

just wondering if it would be very difficult to implement different logos for the dark and the light theme. I created a logo to match the dark theme in green (nice default highlight color for the dark theme). In the light theme where the highlight color is blue the green logo seems not very suitable. (I know I could change the color scheme, but I like the different highlight color).

This is just a question not an issue.

Many thanks for this wonderful theme!

PS.: I could imagine the site to choose logo.png if this is the only logo-file, and for example logo-dark.png and logo-light.png for the appropriate theme if the files exist. Again, just an idea.

**Comment by nicolasprigent** [comment]
hello @christianprim . This is a good suggestion, the problem is that theme color detection (on the os level) is only available on client side (css/javascript). So php that is writing the location of the logo can't be aware of it, not in the first load anyway. Then I could use the theme cookie that I already store to display the correct logo. It's this first load that is annoying because there could be a "popping" logo on the display. I'll investigate on a good solution and let you know.

**Comment by nicolasprigent** [comment]
You can try and test this branch : https://github.com/nicolasprigent/Dokuwiki-Kiwiki-Theme/tree/themed-logo
I've tested it on my side and it works as expected. You just have to upload your custom logos on the root of your install :
- logo.png for default logo (still mandatory for this to work)
- logo-dark.png for dark logo
- logo-light.png for light logo
All 3 logos should have exactly the same size. If they don't, you could have unexpected result.
If you just have logo-dark.png and logo.png for example, the light logo will be default logo.png, so you don't really need to upload 3 files. Just upload one that needs to be replaced on the problematic color scheme.

**Comment by christianprim** [comment]
Wow! It works perfect! I used my logo.png as my dark theme logo and my equally sized logo-light.png for the light theme. You are a real css-genius. Sorry for my late reply.

**Comment by nicolasprigent** [comment]
Great to ear that it worked as expected ! I'll merge the branch for this new feature.
